import cron from 'node-cron';
import { UserModel } from '../../user/models/user/index.js';
import { StoreModel } from '../../store/models/store/store.model.js';
import { CampaignModel } from '../../campaign/models/campaign.model.js';
import { FeedPostModel } from '../../feeds/models/feed/index.js';
import { generateDailySuggestions } from './ai-engagement.service.js';
import { sendEmail } from '../../../core/email.service.js';
import { wrapEmail } from '../../../core/brand-email.js';

async function sendDailySuggestions() {
  try {
    // Get all active marketers with stores
    const stores = await StoreModel.find({ isDeleted: false, isActive: true })
      .select('owner name category analytics').lean();

    // Group by owner
    const byOwner = new Map();
    for (const s of stores) {
      const key = String(s.owner);
      if (!byOwner.has(key)) byOwner.set(key, []);
      byOwner.get(key).push(s);
    }

    let sent = 0;
    for (const [ownerId, ownerStores] of byOwner) {
      const user = await UserModel.findById(ownerId).select('email displayName notifications').lean();
      if (!user?.email) continue;

      const store = ownerStores[0];
      const activeCampaigns = await CampaignModel.countDocuments({ owner: ownerId, status: 'active', isDeleted: false });
      const recentPosts = await FeedPostModel.countDocuments({ author: ownerId, status: 'active', createdAt: { $gte: new Date(Date.now() - 7 * 86400000) } });

      const suggestions = await generateDailySuggestions({
        storeName: store.name,
        category: store.category,
        totalSales: store.analytics?.totalSales || 0,
        totalViews: store.analytics?.totalViews || 0,
        activeCampaigns,
        recentPosts
      });

      if (!suggestions.length) continue;

      const suggestionsHtml = suggestions.map((s, i) =>
        `<tr><td style="padding:8px;border-bottom:1px solid #eee;font-size:14px;color:#333;">
          <strong>${i + 1}.</strong> ${s}
        </td></tr>`
      ).join('');

      const content = `<p style="font-size:15px;">Hi ${user.displayName || 'there'}, here are your daily growth suggestions:</p>
        <table style="width:100%;margin:12px 0;">${suggestionsHtml}</table>
        <p style="font-size:12px;color:#999;">Generated by MarketAI — check your dashboard for more insights.</p>`;

      await sendEmail({
        to: user.email,
        subject: `Your daily growth suggestions for ${store.name}`,
        html: wrapEmail({ title: 'Daily Business Suggestions', content })
      }).catch(() => {});

      sent++;
    }

    console.log(`[ai-suggestions] Sent suggestions to ${sent} marketers`);
  } catch (err) {
    console.error('[ai-suggestions] Error:', err.message);
  }
}

export function initAISuggestionsCron() {
  cron.schedule('0 7 * * *', sendDailySuggestions);
  console.log('[CRON] Scheduled: Daily AI business suggestions (7 AM)');
}
