runtime: nodejs22 # or your Node.js version
env: standard      # This line is usually present for standard environment
service: default
entrypoint: node server.js # or your main app file


env_variables:
  MONGODB_USERNAME: "schooltraz"
  MONGODB_PASSWORD: "$ch00lTraz"
  MONGODB_DATABASE: "marketspase"
  JWTTOKENSECRET: "alexim39"
  EMAILPASS: "$ch00ltraz"
  PAYSTACKTOKEN: "sk_live_2288514c9d501669926c10dc09cff03b11b3bafa"
  PAYSTACK_WEBHOOK_SECRET: "alexim39"